# Generated by Django 2.1.7 on 2024-06-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=50, verbose_name='Task Title')),
                ('task_description', models.TextField(max_length=200, verbose_name='Task Description')),
                ('task_created', models.DateTimeField(auto_now_add=True)),
                ('task_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
    ]
